from typing import Protocol, SupportsIndex, TypeVar, overload

T = TypeVar("T", covariant=True)


class ArrayLike(Protocol[T]):
    def __len__(self) -> int: ...
    @overload
    def __getitem__(self, key: SupportsIndex, /) -> T: ...
    @overload
    def __getitem__(self, key: slice, /) -> "ArrayLike[T]": ...
    def __getitem__(self, key: SupportsIndex | slice, /) -> T | "ArrayLike[T]": ...
